---
- name: install httpd and configuring to host webpage
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Calling the Apache role for installation
      ansible.builtin.import_role:
        name: apache
